version: 0.2

phases:
  pre_build:
    commands:
      - echo Installing cdk dependencies
      - cd ${CODEBUILD_SRC_DIR}/cdk
      - npm ci
      - npm run build
      - npm install aws-cdk -g
      - cdk --version
      - echo Running cdk unit tests
      - npm run test
      - echo Install behave
      - pip install behave

  build:
    commands:
      - echo Downloading lambda layer dependencies
      - pip install --python-version 38 --only-binary=":all:" --target ${CODEBUILD_SRC_DIR}/test/lambda/layer/python/lib/python3.8/site-packages requests
      - echo Deploy CDK stacks
      - cd ${CODEBUILD_SRC_DIR}/cdk
      - cdk deploy --all

  post_build:
    commands:
      - echo Running BDD tests
      - cd ${CODEBUILD_SRC_DIR}/features
      - behave
      - echo Update API URL in iot.html and upload
      - API_URL=$(aws cloudformation list-exports --query "Exports[?Name=='iot-api-url'].Value" --no-paginate --output text)
      - sed -i "s%<API_URL>%$API_URL%g" ${CODEBUILD_SRC_DIR}/site/iot.html
      - aws s3 cp ${CODEBUILD_SRC_DIR}/site/iot.html s3://sebastiandengler.de/iot.html


