version: 0.2

phases:
  install:
    commands:
      - cd ${CODEBUILD_SRC_DIR}/cdk
      - npm install
      - cdk --version

  build:
    commands:
      - cd ${CODEBUILD_SRC_DIR}/cdk
      - cdk deploy