version: 0.2

phases:
  pre_build:
    commands:
      - cd ${CODEBUILD_SRC_DIR}/cdk
      - npm ci
      - npm run build
      - npm install aws-cdk -g
      - cdk --version
      - npm run test

  build:
    commands:
      - pip install --python-version 38 --only-binary=":all:" --target ./test/lambda/layer/python/lib/python3.8/site-packages requests
      - cd ${CODEBUILD_SRC_DIR}/cdk
      - cdk deploy --all
