version: 0.2

phases:
  pre_build:
    commands:
      - echo Installing cdk dependencies
      - cd ${CODEBUILD_SRC_DIR}/cdk
      - npm ci
      - npm install aws-cdk -g
      - cdk --version
      - echo Running cdk unit tests
      - npm run test
      - echo Install behave
      - pip install behave

  build:
    commands:
      - echo Deploy CDK stacks
      - cd ${CODEBUILD_SRC_DIR}/cdk
      - cdk deploy --all --require-approval never

  post_build:
    commands:
      - echo Running BDD tests
      - cd ${CODEBUILD_SRC_DIR}/features
      - behave
      - echo SUCCESS
