version: 0.2

env:
  shell: bash

phases:
  install:
    runtime-versions:
      nodejs: 12.x

  pre_build:
    commands:
      - cd ${CODEBUILD_SRC_DIR}/cdk
      - npm ci
      - npm run build
      - cdk --version
      - npm install aws-cdk -g
      - npm run test

  build:
    commands:
      - cd ${CODEBUILD_SRC_DIR}/cdk
      - pip install --python-version 38 --only-binary=":all:" --target ./test/lambda/layer/python/lib/python3.8/site-packages requests
      - cdk deploy --all
